### ISSUE TITLE
"Prepare host" button will not function without valid "Alteeve Enterprise Key"  - `striker-ui` 

### ISSUE THREAD

**Issue by maholloway** [ClusterLabs/anvil#670] opened 2024-06-02 17:31 UTC
Hello,

This issue pertains to the following package versions:
anvil-core version 2.92-1.2.9cfa
anvil-node version 2.92-1.2.9cfa
anvil-striker version 2.92-1.2.9cfa

I have followed the, "Build an M3 Anvil! Cluster" guide on the wiki [here](https://wiki.alteeve.com/index.php?title=Build_an_M3_Anvil!_Cluster).

All steps in the guide work as expected until the [Initializing Subnodes](https://wiki.alteeve.com/index.php?title=Build_an_M3_Anvil!_Cluster#Initializing_Subnodes) step.

I have two subnodes, 192.168.1.175 and 192.168.1.176 on the ifn. They both have `anvil-node` installed successfully as per the guide's previous steps.

Testing access works. The "Host name" field populates as expected, with a property formatted FQDN.

The next step is unavailable, due to a non-functional "Prepare host" button. Screenshot:

![2024-06-02-07-19-31-190](https://github.com/ClusterLabs/anvil/assets/11896557/314be5cc-9171-4762-81c6-a896a1bb6a7a)

@digimer suggests @ylei-tsubame will know what might be the matter here. If folks need any more info or have further questions for me please let me know and I'll help however I can.

**Comment by maholloway** [comment] 2024-06-02 18:49
[This thread on the hardware vendor's user support forum](https://forum.odroid.com/viewtopic.php?p=366650&sid=798f3c9e1c0b23c5d647052390777f2e#p366650) may or may not be related.

To test, I've successfully flashed the latest version of the ODROID H3+ main and net board BIOSes using [this doc](https://wiki.odroid.com/odroid-h3/hardware/h3_bios_update].

Via testing with this new BIOS version on one of my two boards I can confirm `dmidecode --string system-uuid` output has changed from 
03000200-0400-0500-0006-000700080009
to
1e000000-4506-7407-0101-001e06450775

This will likely resolve some "flapping" I observed in the database and in `striker-ui-api` logs, meaning only one node would display at a time (because of the db index in postgres?) and the hostname would alternate between mh-a01n01.libre.audio and mh-a01n02.libre.audio.

I'll try initializing the subnode running on the board with the updated BIOS shortly.

**Comment by maholloway** [comment] 2024-06-03 00:03
The issue persists after reinstalling `anvil-node` on the subnode board with the updated bios.

All 3 anvil systems now have unique uuids (both subnodes would have had the same one prior to the bios update on subnode 1)
![2024-06-02-19-51-24-020](https://github.com/ClusterLabs/anvil/assets/11896557/6d7dcfea-d7dc-4d10-87f5-df6be1ea2d55)

The apparent `striker-ui` issue still persists as depicted below:
![2024-06-02-19-50-31-574](https://github.com/ClusterLabs/anvil/assets/11896557/dedcde0e-dd23-400c-ba99-a40b736a2ec6)

**Comment by ylei-tsubame** [comment] 2024-06-07 23:30
The problem is the host UUID. It's not considered as a valid UUIDv4 by spec. I can reduce the restrictions on the UUID test to allow these.

**Comment by ylei-tsubame** [comment] 2024-06-08 00:16
Patch made; should be merged when CI unblocks.

**Comment by maholloway** [comment] 2024-06-11 21:10
Fantastic thanks Yan! I'll test it out once the change is integrated as you mentioned.

Mike

**Closed** 2024-06-12 23:13 UTC
Labels: bug, urgent
