### ISSUE TITLE
When creating fence devices, don't mask 'passwd_script'

### ISSUE THREAD

**Issue by digimer** [ClusterLabs/anvil#563] opened 2024-01-20 20:43 UTC
I suspect there's a regex looking for 'passw'? If the end is '_script', it shouldn't be masked.

![image](https://github.com/ClusterLabs/anvil/assets/189162/323db764-349c-4563-8318-c584248213c4)

**Comment by ylei-tsubame** [comment] 2024-03-28 17:17
Duplicate of #525

**Closed by ylei-tsubame** 2024-03-28 17:17 UTC
Labels: enhancement, normal
